### ISSUE TITLE
Document OAuth2 on react native

### ISSUE THREAD

**Issue by ekryski** [feathersjs/authentication#120]
It works and people have got it working but can make it easier or we should provide a guide.

@catalinmiron [put together a gist](https://gist.github.com/catalinmiron/be093c3ab91589777af5) showing how you can do it. We should just tighten it up a bit and add it to a guide.

**Comment by farwayer** [comment]
One note about @catalinmiron gist: it will trigger `getTheDate()` 3 times because title change also triggers `onNavigationStateChange()`. Didn't tested on iOS yet but on Android `onNavigationStateChange()` will be called with `""`, `"http://.../auth/success#_=_"` and `"Feathers Authentication Success"` titles for the same `http://.../auth/success#_=_` url.

**Comment by catalinmiron** [comment]
This was testen only on iOS. About the get method, you might be right. It's a fast inplementation just to get an idea around oauth in react native. If you want I can make a full example with better code.

**Comment by farwayer** [comment]
You can check if title is empty to prevent calling method several times.

It is working solution but not ideal. Some things I dislikes:
1. You need to enable REST provider on server. It is redundant if you are using sockets only
2. Native cookie module to get token
3. Checking state of WebView and hardcoded urls (`/auth/facebook` and `/success`)
4. Authentication via REST and then via socket
5. You must change server url in facebook app config every time you move featchers server to another ip/domain

I can propose more elegant way guys. But it may (and imho will) require modification of `auth` service to make it more flexible.
We can use internal mobile application url (or WebView state change as option) to get facebook response `code` and send it via socket to feathers server. One (or two - see below) requests to our server only.

Scenario:
1. Add listener to [Linking](https://facebook.github.io/react-native/releases/next/docs/linking.html) `url` event
2. Open WebView or even external browser with OAuth url (we can make url manually or request  from feathers server for more flexibility). We will use app scheme (`myapp://auth`) for `redirect_url`
3. Catch redirect params from `Linking` url callback
4. Send params via socket (or REST) to feathers server and get JWT token and user data from response

Pros:
1. REST not required
2. No external libs
3. No hardcoded server urls
4. Less browser redirects
5. One (or two) requests to feathers server only
6. Server url in facebook app config is app url and constant
7. Make things in more automatic way (without parsing cookies, checking WebView state)

Cons:
1. Config app url or checking WebView state

**Comment by sscaff1** [comment]
@farwayer can you post a simple example?

**Comment by sscaff1** [comment]
I see that to implement @farwayer suggestion it would take some changes to feathers. Here is another example for those looking for guidance on the issue. 

https://github.com/sscaff1/hopePing/blob/master/src/scenes/LoginScene.js

It's very similar to @catalinmiron suggestion but CookieManager has since been updated. The above reflects the update. Also I avoid triggering this.authenticate multiple times by setting state immediately following getting my cookie values. Hope this helps.

**Comment by muvhaus-sl** [comment]
Sscaff1 LoginScene is pretty accurate. It works as long as the provider supports WebViews.
This is no longer the case for Google OAuth2. If you try to launch using a WebView it returns an error message with:
403 Error
Dissalowed Agent

This became effective in September 2016 or so.

The method suggested by Farwayer, of using the App url scheme and the native browser seems to be the way to go.

**Comment by daffl** [comment]
This has also been improved in Feathers v4 authentication which allows to authenticate with an existing oAuth token the same way as with any other strategy (and without additional configuration necessary).

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
