### ISSUE TITLE
Server-side socket re-auth

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/authentication#377]
I think @bertho-zero might have posted a good start at automatically authenticating sockets https://github.com/feathersjs/feathers-authentication/issues/372#issuecomment-267571352

It depends on cookies being enabled.

**Comment by ekryski** [comment]
Thanks for creating a new issue to track this @marshallswain! I have a solution locally.

You don't need cookies if you have already authenticated and have a valid token in local storage. It should re-auth on page refresh. If you are using SSR and have a cookie with a valid token the app should also auto authenticate.

The real issue is around whether your `accessToken` has expired and the user refreshes the page. In that case, I think on web the user needs to login again (either by magic link, phone number, email+password, oauth, etc.). On mobile, if you are securely storing your `clientId` and `clientSecret` or using a refresh token you should be able to re-authenticate on behalf of the user.

I'll try and push up my last couple auth client and server changes in the next couple days now that I am refreshed from much Christmas cheer! 🎅

**Comment by tb** [comment]
Hi, I have similar problem - I have google callback redirected me to react app, the token is cookie, but the sockets are not authenticated https://github.com/tb/feathers-react-todos/blob/master/client/src/client.js I am also not sure if I have the the server part configured properly - https://github.com/tb/feathers-react-todos/blob/master/src/app.js#L32 I had to add custom hook to get it working, see https://github.com/tb/feathers-react-todos/blob/master/src/hooks/index.js#L20 Its based on https://github.com/feathersjs/feathers-authentication/issues/223#issuecomment-226209456

**Comment by mdorta-hiades** [comment]
How I can refresh the token?

**Comment by bertho-zero** [comment]
@ekryski The token in the localStorage is valid and not expired, it's the same that in the cookie.

The problem is that without this socket.io middleware, I would have to call `app.authenticate()` and include the rest of the app in `.then`. Or else I could not be directly connected and I would get a visual glitch in the browser.
