### ISSUE TITLE
Accidentally modifying the find results in a hook hides error of not finding user

### ISSUE THREAD

**Issue by Sieabah** [feathersjs/authentication#557]
### Steps to reproduce

_app.hooks.js_
```
    hooks.after = {
        all: (hook) => { if(hook.results) hook.results = {results: hook.results}; return hook; }
    }
```

### Expected behavior

An error or warning should be logged that the results object isn't in the expected form

### Actual behavior

Ignores malformed object and considers the user _not found_ and creates a new one in the database (if unique keys are not enforced)

### System configuration

**NodeJS version**:
Any

**Operating System**:
Any

**Comment by daffl** [comment]
This should be more easily to customize now with Feathers v4 authentication.

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
