### ISSUE TITLE
Authenticate with any/multiple entities

### ISSUE THREAD

**Issue by yongching** [feathersjs/authentication#559]
Have this function be implemented? [#282](https://github.com/feathersjs/feathers-authentication/issues/282)

**Comment by daffl** [comment]
This has been addressed a while ago and made more flexible by authentication in Feathers v4. Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
