### ISSUE TITLE
Authenticate user on register (return token with user creation)

### ISSUE THREAD

**Issue by robertbart** [feathersjs/authentication#562]
### Steps to reproduce

I would like to add a token to the register response on when sending a ```post``` to ```/users```.

I attempted to add a hook (similar one to the found in the ```authentication.js``` file) to the ```users.hooks.js``` create endpoint but with no success.

The hook from ```create``` from ```authentication.js```:

```javascript
  app.service('authentication').hooks({
    before: {
      create: [
        authentication.hooks.authenticate(config.strategies)
      ],
      remove: [
        authentication.hooks.authenticate('jwt')
      ]
    }
  });
```

**Comment by robertbart** [comment]
I found an alternative solution. I call the authentication service as an after hook on the user create service.

```javascript
after: {
    all: [
      commonHooks.when(
        hook => hook.params.provider,
        commonHooks.discard('password')
      )
    ],
    find: [],
    get: [],
    create: [ function(hook) {
      const data = {
        username: hook.data.username,
        password: hook.data.password2,
        strategy: 'local'
      };

      return hook.app.service('authentication').create(data).then(page => {
        page.user = hook.result;
        hook.result = page;
        return Promise.resolve(hook);
      });
    } ],
    update: [],
    patch: [],
    remove: []
  },
```

But I get some unexpected behaviour. The token I'm given works but does not add the ```userId``` in it's payload.

**Comment by marshallswain** [comment]
You need to pass an object with the user data to the second argument of the `create` method:

```
const params = { user: hook.result }
return hook.app.service('authentication').create(data, params).then...
```
I think that should do the trick for you.

**Comment by robertbart** [comment]
I have attempted to do what you recommended and it didn't work. Nothing was added to the token payload.

Further I have attempted to change the params into:
```javascript
const params = { userId: hook.result._id };
```
But this didn't work either.

**Comment by marshallswain** [comment]
Try this, maybe?  https://docs.feathersjs.com/guides/auth/recipe.customize-jwt-payload.html

**Comment by robertbart** [comment]
Unsure how to implement this.

Do service calls call the hooks that are given to them when called through ```hook.app.service(...```?

**Comment by Ernoff** [comment]
The JWT is divided into three parts.
1) Header
2) Payload
3) Signature

Based on the two Token you posted, It shows that the difference lies in the signature. Header and Payload is the same.

Looking at the signature now, it is the hash of the header, the payload and your secret. Since the first two is basically the same, It is safe to say the the token on user register call used a different secret for encryption. 

Judging from the conversation above, it seems (wild guess) that you used the userID as secret in user register call. Look into that.

I hope this helps you debug

**Comment by AlbertNavasardyan** [comment]
@robertbart you should put { userId: hook.result._id } in payload of params.
something like 
```
const { accessToken } = await hook.app.service('authentication').create({}, {
            payload: { userId: hook.result._id },
          });
```

**Comment by shomalgan** [comment]
hook.result didn't work for me!
the actual result sent to the user is **hook.dispatch**, I updated **hook.dispatch**!

**Comment by daffl** [comment]
This can be done with Feathers v4 authentication by calling `authService.authenticate`.

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
