### ISSUE TITLE
Persist auth tokens on db

### ISSUE THREAD

**Issue by NeonXP** [feathersjs/authentication#569]
Hello. Is it possible to authorise users by tokens (i.e. generated uuid), that stored on DB (dedicated sessions collection or "tokens" field on users collection)? Without JWT, that stores only on client-side.

Pros: You can invalidate user session on server-side (i.e. if user changed password we need to logout him) or from another session ("Logout from other devices" feature)
Cons: Need to check token on every request.

**Comment by daffl** [comment]
Token Blacklisting functionality is being tracked in #73 there is some discussion there but currently you'd still have to implement that yourself manually (with a custom JWT verifier).

**Comment by TimNZ** [comment]
I'm trying to follow all the discussions around JWT token revocation.

In the traditional world sessions are tracked in a table, and can be revoked easily and immediately.

How did Featherjs end up with an architecture that doesn't support this?

**Comment by daffl** [comment]
It ended up with that by choosing [JWT](https://jwt.io/) as the authentication mechanism which has its own advantages and disadvantages. By architecture you still have the option to _choose a different authentication mechanism_ but most "traditional" mechanisms are much more difficult to use when it comes to integrating websockets transparently.

**Comment by TimNZ** [comment]
Brainstorming.

Since you guys have done a good job of making a pipeline  that can be hooked into at various points, can I create a 'feathers-authentication-session' module that can implement traditional session support e.g. persisted, storing generated JWT tokens, and this is checked first and the JWT refused if it doesn't exist?
I presume failed JWT result in the client SDK's clearing it out from storage?

This should be invisible to clients and achieves what people are expecting?

**Comment by TimNZ** [comment]
I am tracing through the authentication module now to bullet point the flow to see if this works and how to do it.
