### ISSUE TITLE
The authentication chain terminates on first failure.

### ISSUE THREAD

**Issue by queuetue** [feathersjs/authentication#623]
### Steps to reproduce

In v 2.1.0 of `@feathersjs/authentication` , when multiple authentication methods are used in a chain

```
module.exports = {
    before: {
        all: [authenticate(['jwt', 'anon'])],
```

the chain will terminate on the first failure.  In the example above, `anon` will never be tested.

An (unacceptable) suggested solution is shown in feathersjs/authentication#622 .

**Comment by queuetue** [comment]
The initial cause of this was the same symptom reported initially in #577 ("No auth token" in console), although I think our causes are different.

**Comment by daffl** [comment]
Feathers v4 authentication requires a `strategy` parameter but also allows to fully customize the authentication service to any other requirement.

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
