### ISSUE TITLE
secret should be optional if a custom verifier function is provided

### ISSUE THREAD

**Issue by schettino** [feathersjs/authentication#658]
### Steps to reproduce
feathers g app
feathers g authentication

### Expected behavior
If I'm passing a custom function to verify the token, I want to override the verification that the lib does, Verification is about checking whether the signatures matches. So, I  am not able to take care of this, the app throws an error when starting. If I use a secret to prevent that error, the custom function is not called because there may be a misconception here. The lib verifies the signature before call the CustomVerifier. Instead, it should be named as a custom validation function (a Validator property instead of Verifier), or provide us a full control of the verification flow.

**Module versions** (especially the part that's not working):
    "@feathersjs/authentication": "^2.1.3",
    "@feathersjs/authentication-jwt": "^2.0.0",
    "@feathersjs/configuration": "^1.0.2",
    "@feathersjs/errors": "^3.3.0",
    "@feathersjs/express": "^1.2.0",
    "@feathersjs/feathers": "^3.1.3",
    "@feathersjs/socketio": "^3.2.0",

**NodeJS version**:
8.9.3

**Comment by daffl** [comment]
Feathers v4 authentication strategies can now be fully customized including making all options dynamic and optional. Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
