### ISSUE TITLE
client side authentication

### ISSUE THREAD

**Issue by lean** [feathersjs/authentication#697]
I have a simple question. If I have authentication only on the client side, the scenario could be from a SPA, a mobile application, using hello.js or Firebase Authentication. What would be the best way to handle this?

**Comment by daffl** [comment]
Unfortunately this simple question does not have a simple answer 😉 There are many different ways to approach this but in any case, the server needs a way to verify the authentication information with the remote provider. What does the library/service you are using recommend for this?

**Comment by lean** [comment]
I'm get the credentials of Google with the Google oAuth Sign-in / Log-in. In react for example: https://www.npmjs.com/package/react-google-login

**Comment by daffl** [comment]
This should be more easily possible now with Feathers v4 authentication where additionally to oAuth browser redirect the oAuth strategies can also be used with an existing oAuth access token.

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
