### ISSUE TITLE
SocketEntity type mismatch on update

### ISSUE THREAD

**Issue by thinksentient** [feathersjs/authentication#699]
I've run into this weird problem, were the **entity** in [`updateEntity()`](https://github.com/feathersjs/authentication/blob/6e011d6042615662e18a1add3a29958f7f28ab31/lib/socket/update-entity.js) is a "flat" object, but the **socketEntity** is a model instance. This breaks the ability to patch fields through the users service. The model does have associations so the `sequelize.raw = false;` flag is set (in case that makes a difference).

Can't find a way to force the entity to come through as a model instance despite context.result for users find/get/patch being forced into one in users.hooks.js. Could someone point me in the right direction or confirm this is a bug?

**Comment by thinksentient** [comment]
Thanks! Going all flat rather than all instance solved the problem for me.

**Comment by daffl** [comment]
This has also been improved in Feathers v4 authentication.

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
